/* Copyright(C) 2007 National Institute of Informatics, All rights reserved.*/
CREATE USER SA PASSWORD "" ADMIN DROP TABLE PAYMENT IF EXISTS;
DROP TABLE AVAILABLEQTY IF EXISTS;
DROP TABLE RESERVATION IF EXISTS;
DROP TABLE ROOM IF EXISTS;
CREATE TABLE PAYMENT(
    ROOMNUMBER VARCHAR(50) NOT NULL,
    STAYINGDATE VARCHAR(20) NOT NULL,
    AMOUNT INTEGER,
    STATUS VARCHAR(10),
    CONSTRAINT ROOMNUMBER_STAYINGDATE PRIMARY KEY(ROOMNUMBER, STAYINGDATE)
);
CREATE TABLE AVAILABLEQTY(
    DATE VARCHAR(20) NOT NULL PRIMARY KEY,
    QTY_SINGLEROOM INTEGER,
    QTY_TWINROOM INTEGER,
    QTY_TRIPLEROOM INTEGER,
    QTY_KINGROOM INTEGER,
    QTY_PRESIDENTIALSUITE INTEGER,
    QTY_JAPANESEROOM INTEGER,
    QTY_DISABLEDROOM INTEGER
);
CREATE TABLE RESERVATION(
    RESERVATIONNUMBER VARCHAR(50) NOT NULL PRIMARY KEY,
    STAYINGDATE VARCHAR(20),
    ROOMTYPE VARCHAR(20),
    STATUS VARCHAR(10)
);
CREATE TABLE ROOM(
    ROOMNUMBER VARCHAR(50) NOT NULL PRIMARY KEY,
    STAYINGDATE VARCHAR(20),
    ROOMTYPE VARCHAR(20)
);
INSERT INTO ROOM
VALUES('1001', '', 'SingleRoom');
INSERT INTO ROOM
VALUES('1002', '', 'SingleRoom');
INSERT INTO ROOM
VALUES('1003', '', 'SingleRoom');
INSERT INTO ROOM
VALUES('1004', '', 'SingleRoom');
INSERT INTO ROOM
VALUES('2001', '', 'TwinRoom');
INSERT INTO ROOM
VALUES('2002', '', 'TwinRoom');
INSERT INTO ROOM
VALUES('2003', '', 'TwinRoom');
INSERT INTO ROOM
VALUES('2004', '', 'TwinRoom');
INSERT INTO ROOM
VALUES('3001', '', 'TripleRoom');
INSERT INTO ROOM
VALUES('3002', '', 'TripleRoom');
INSERT INTO ROOM
VALUES('4001', '', 'KingRoom');
INSERT INTO ROOM
VALUES('4002', '', 'KingRoom');
INSERT INTO ROOM
VALUES('4003', '', 'KingRoom');
INSERT INTO ROOM
VALUES('5001', '', 'PresidentialSuite');
INSERT INTO ROOM
VALUES('6001', '', 'JapaneseRoom');
INSERT INTO ROOM
VALUES('6002', '', 'JapaneseRoom');
INSERT INTO ROOM
VALUES('6003', '', 'JapaneseRoom');
INSERT INTO ROOM
VALUES('7001', '', 'DisabledRoom');